services:
    bookboon.cache:
        public: true
        class: Symfony\Component\Cache\Simple\RedisCache
        arguments:
          - '@default_redis_provider'
          - 'api'
          - 1800

    bookboon.handlerstack:
        class: GuzzleHttp\HandlerStack
        factory: ['GuzzleHttp\HandlerStack', 'create']

    Bookboon\ApiBundle\Client\AccessTokenClient:
      public: true
      lazy: true
      factory: [ 'Bookboon\ApiBundle\Service\ApiFactory', createOauth ]
      arguments:
        - '@Bookboon\ApiBundle\Helper\ConfigurationHolder'
        - '@bookboon.cache'
        - '@monolog.logger.api'
        - '@bookboon.handlerstack'
      tags:
        - { name: monolog.logger, channel: api }

    Bookboon\ApiBundle\Client\RawClient:
      public: true
      autowire: true
      bind:
        GuzzleHttp\HandlerStack: '@jsonldclient.handlerstack'

    Bookboon\ApiBundle\Helper\GuzzleDecorator:
      class: GuzzleHttp\HandlerStack
      decorates: jsonldclient.handlerstack
      factory: ['Bookboon\ApiBundle\Helper\GuzzleDecorator', 'decorate']
      bind:
        GuzzleHttp\HandlerStack: '@.inner'
        Bookboon\ApiBundle\Helper\ConfigurationHolder: '@Bookboon\ApiBundle\Helper\ConfigurationHolder'
        Symfony\Component\HttpFoundation\RequestStack: '@request_stack'
